# Generated by Django 2.1.7 on 2019-04-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Digit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base64_data', models.TextField()),
                ('category', models.TextField()),
                ('entry_type', models.CharField(max_length=100)),
            ],
        ),
    ]
